name: Auto Publish

on:
  workflow_dispatch:
  repository_dispatch:
    types: [release]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: pip install httpx

      - name: Download MSIX
        run: |
          wget --header="Authorization: Bearer ${{ secrets.SIGNPATH_TOKEN }}" -O Snap.Hutao.${{ github.event.client_payload.version }}.msix ${{ github.event.client_payload.download_link }}

      - name: Generate SHA256 Checksums
        run: sha256sum *.msix | awk '{print $1}' > SHA256SUMS

      - name: Generate update logs
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          ZULIP_API_KEY: ${{ secrets.ZULIP_API_KEY }}
          ZULIP_EMAIL: ${{ secrets.ZULIP_EMAIL }}
          ZULIP_STREAM: ${{ secrets.ZULIP_STREAM }}
          ZULIP_TOPIC: ${{ secrets.ZULIP_TOPIC }}
          VERSION: ${{ github.event.client_payload.version }}
        run: |
          python ${{ github.workspace }}/main.py

      - name: Create Github release
        id: github_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ github.event.client_payload.version }}
          target_commitish: main
          name: ${{ github.event.client_payload.version }}
          body_path: release_body.md
          prerelease: false
          repository: DGP-Studio/Snap.Hutao
          files: |
            Snap.Hutao.${{ github.event.client_payload.version }}.msix
            SHA256SUMS
