name: Auto Publish

on:
  workflow_dispatch:
  repository_dispatch:
    types: [release]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Get PAT Token
        run: |
          token=`curl -X GET '${{ secrets.PAT_URL }}' --header 'token: ${{ secrets.GENERIC_TOKEN }}' | jq -r '.pat'`
          echo "PAT_TOKEN=${token}" >> "$GITHUB_ENV"
          echo "GITHUB_TOKEN=${token}" >> "$GITHUB_ENV"

      - name: Download MSIX
        run: |
          wget --header="Authorization: Bearer ${{ secrets.SIGNPATH_TOKEN }}" -O Snap.Hutao.${{ github.event.client_payload.version }}.msix ${{ github.event.client_payload.download_link }}

      - name: Generate update logs
        env:
          VERSION: ${{ github.event.client_payload.version }}
        run: |
          python ${{ github.workspace }}/main.py

      - name: Upload msix to object stores
        uses: hutao-cdn/upload@v1
        with:
          file_path: Snap.Hutao.${{ github.event.client_payload.version }}.msix
          key: Snap.Hutao.${{ github.event.client_payload.version }}.msix
          post_action: preheat
        env:
          SNAP_HUTAO_CDN_TOKEN: ${{ secrets.SNAP_HUTAO_CDN_TOKEN }}

      - name: Post Generate update logs
        run: |
          python ${{ github.workspace }}/post.py

      - name: Create Github release
        id: github_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.client_payload.version }}
          target_commitish: main
          name: ${{ github.event.client_payload.version }}
          body_path: release_body.md
          prerelease: false
          repository: DGP-Studio/Snap.Hutao
          files: |
            Snap.Hutao.${{ github.event.client_payload.version }}.msix
